import Navbar from '../components/Navbar'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import './LegalPage.css'

export default function TermsOfService() {
  return (
    <div className="legal-page">
      <Banner />
      <Navbar theme="page" />

      <div className="legal-content">
        <h1>Terms of Service</h1>
        <p className="legal-meta">
          <strong>Effective date:</strong> To be confirmed upon launch &nbsp;·&nbsp; <strong>Last updated:</strong> August 5, 2026
        </p>

        <div className="legal-notice">
          <strong>Coming Soon —</strong> The EVOARX app and store are not yet available to the public. These Terms are published in advance so you can review them before launch. Store-specific terms (Parts B) will become applicable once the store opens.
        </div>

        <p>These Terms of Service ("Terms") govern your use of the EVOARX mobile application, evoarx.app, and our merchandise store (together, the "Services"), operated by EVOARX, a business registered in the Province of Ontario, Canada. By using any of the Services, you agree to these Terms.</p>

        <hr />

        <h2>1. Eligibility</h2>
        <p>You must be at least 13 years old to create an App account. By creating an account, you confirm that the date of birth you provide is accurate. To purchase merchandise from the Store, you must be of the age of majority in your province/jurisdiction, or purchasing with the involvement of a parent or guardian.</p>

        <hr />

        <h2>2. Description of Service</h2>
        <ul>
          <li><strong>App:</strong> EVOARX generates AI-assisted workout programs based on information you provide (fitness goals, experience, equipment, and self-reported health/safety screening answers) and lets you log workouts and share activity with other users.</li>
          <li><strong>Store:</strong> EVOARX sells branded apparel and merchandise, processed through our payment processor, Stripe.</li>
        </ul>

        <hr />

        <h2>Part A — App Terms</h2>

        <h3>A1. Medical Disclaimer & Assumption of Risk</h3>
        <p>EVOARX and any program it generates are provided for general fitness purposes only and do not constitute medical advice, diagnosis, or treatment. You should consult a physician or other qualified healthcare professional before beginning any exercise program, especially if you have a pre-existing health condition, injury, or physical limitation.</p>
        <p>Physical exercise carries an inherent risk of injury. By using the App, you voluntarily assume all risks associated with exercise and agree that EVOARX is not responsible for any injury or health issue that may result from following a program generated by the App.</p>

        <h3>A2. AI-Generated Content</h3>
        <p>Workout programs are generated by an AI system based on the information you provide. While we aim for programs to be safe and appropriate, AI-generated content may occasionally be inaccurate or unsuitable for your specific circumstances. Use your judgment and stop any exercise that causes pain or discomfort.</p>

        <h3>A3. User Accounts</h3>
        <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You may permanently delete your account and associated data at any time from Settings → Data and Privacy.</p>

        <h3>A4. User Conduct</h3>
        <p>You agree not to post content that is unlawful, abusive, or infringes on others' rights, and not to misuse the App's social features (e.g., impersonation, harassment, spam).</p>

        <hr />

        <h2>Part B — Store Terms</h2>
        <p><em>The store is not yet open. The following terms will apply once it launches.</em></p>

        <h3>B1. Products & Descriptions</h3>
        <p>We try to describe and display merchandise accurately, but we do not warrant that product descriptions, images, or other content are error-free. Colors may vary slightly from photos due to display settings.</p>

        <h3>B2. Orders, Pricing & Payment</h3>
        <ul>
          <li>All prices exclude applicable taxes and shipping unless stated otherwise; these are disclosed at checkout before you confirm your order.</li>
          <li>Payment is processed by Stripe. By placing an order, you authorize us to charge your payment method for the total order amount.</li>
          <li>We reserve the right to refuse or cancel any order, including for suspected fraud, pricing errors, or insufficient stock.</li>
          <li>An order is not accepted until we send you a confirmation email.</li>
        </ul>

        <h3>B3. Shipping & Delivery</h3>
        <ul>
          <li>Shipping regions and estimated delivery times will be confirmed at launch.</li>
          <li>Estimated delivery times are estimates only; we are not liable for carrier delays outside our control.</li>
          <li>Risk of loss and title pass to you upon delivery to the shipping carrier.</li>
        </ul>

        <h3>B4. Returns, Exchanges & Refunds</h3>
        <ul>
          <li>You may request a return or exchange within 30 days of delivery, provided the item is unworn, unwashed, and in its original condition with tags attached.</li>
          <li>To start a return, contact evoarx@gmail.com with your order number.</li>
          <li>Approved refunds are issued to your original payment method via Stripe within 5–10 business days of us receiving the returned item.</li>
          <li>This section does not limit any statutory consumer rights you have under Ontario's <em>Consumer Protection Act, 2002</em> or other applicable law.</li>
        </ul>

        <h3>B5. Supplier Information (Ontario Internet Sales Disclosure)</h3>
        <ul>
          <li><strong>Legal name:</strong> EVOARX</li>
          <li><strong>Business address:</strong> To be provided upon launch</li>
          <li><strong>Email:</strong> evoarx@gmail.com</li>
          <li><strong>Phone:</strong> To be provided upon launch</li>
        </ul>

        <hr />

        <h2>Part C — General Terms</h2>

        <h3>C1. Intellectual Property</h3>
        <p>The EVOARX name, logo, App, Site, and Store content are owned by EVOARX and protected by copyright and trademark law. You may not copy, reproduce, or create derivative works from our branding or content without our written permission.</p>

        <h3>C2. Limitation of Liability</h3>
        <p>To the fullest extent permitted by law, EVOARX and its developers are not liable for any indirect, incidental, or consequential damages beyond the amount you paid to EVOARX for the specific product or service giving rise to the claim. The Services are provided "as is" and "as available," without warranties of any kind.</p>
        <p>Nothing in these Terms limits liability that cannot be excluded under applicable Ontario or Canadian consumer protection law.</p>

        <h3>C3. Indemnification</h3>
        <p>You agree to indemnify and hold EVOARX harmless from any claims, damages, or expenses (including reasonable legal fees) arising from your misuse of the Services or violation of these Terms.</p>

        <h3>C4. Termination</h3>
        <p>We may suspend or terminate your access to the App for violations of these Terms. You may stop using the Services and delete your account at any time.</p>

        <h3>C5. Governing Law</h3>
        <p>These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein. You and EVOARX agree to submit to the exclusive jurisdiction of the courts located in Ontario, Canada for any dispute not otherwise resolved.</p>

        <h3>C6. Changes to These Terms</h3>
        <p>We may update these Terms from time to time. Material changes will be reflected by a new "Last updated" date above, and App users will be presented with a new terms version for re-consent. Continuing to use the Services after a change means you accept the updated Terms.</p>

        <h3>C7. Contact</h3>
        <p>Questions about these Terms can be sent to evoarx@gmail.com.</p>
      </div>
      <Footer />
    </div>
  )
}
